FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port Next.js runs on
EXPOSE 3000

# Run the application in development mode with hot reloading
CMD ["npm", "run", "dev"] 